## PAQUETERÍAS BÁSICAS

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#### CONFIGURACIÓN DE SETS

In [91]:
train = pd.read_csv('train_clean.csv')
train['TripType'] = train['TripType'].astype('category')
train.head()

,TripType,VisitNumber,Weekday,1-HR PHOTO,ACCESSORIES,AUTOMOTIVE,BAKERY,BATH AND SHOWER,BEAUTY,BEDDING,...,PRE PACKED DELI,PRODUCE,SEAFOOD,SEASONAL,SERVICE DELI,SHOES,SPORTING GOODS,SWIMWEAR/OUTERWEAR,TOYS,WIRELESS
0,3,106,Friday,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,3,121,Friday,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,153,Friday,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,162,Friday,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,3,164,Friday,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [93]:
X_train = train.iloc[:,2:len(train.columns)]
X_train = pd.get_dummies(X_train, 'Weekday')
len(X_train.columns)

68

In [94]:
X_test = test.iloc[:,1:len(train.columns)]
X_test = pd.get_dummies(X_test, 'Weekday')
len(X_test.columns)

68

In [17]:
y_train = train['TripType']
y_train.head()

0    999
1     30
2     26
3      8
4      8
Name: TripType, dtype: category
Categories (38, int64): [3, 4, 5, 6, ..., 42, 43, 44, 999]

In [24]:
test = pd.read_csv('test_clean.csv')
test.head()

,VisitNumber,Weekday,1-HR PHOTO,ACCESSORIES,AUTOMOTIVE,BAKERY,BATH AND SHOWER,BEAUTY,BEDDING,BOOKS AND MAGAZINES,...,PRE PACKED DELI,PRODUCE,SEAFOOD,SEASONAL,SERVICE DELI,SHOES,SPORTING GOODS,SWIMWEAR/OUTERWEAR,TOYS,WIRELESS
0,1,Friday,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,2,Friday,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Friday,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,Friday,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,6,Friday,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [95]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

### MODELOS SKLEARN

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
seed = 1

In [72]:
sample = pd.read_csv('sample_submission.csv')

In [113]:
sample.head()

,VisitNumber,TripType_3,TripType_4,TripType_5,TripType_6,TripType_7,TripType_8,TripType_9,TripType_12,TripType_14,...,TripType_36,TripType_37,TripType_38,TripType_39,TripType_40,TripType_41,TripType_42,TripType_43,TripType_44,TripType_999
0,1,0.037595,0.004004,0.042458,0.014927,0.058300,0.127298,0.094512,0.002517,0.000018,...,0.032067,0.028682,0.029086,0.104883,0.072947,0.006162,0.020575,0.008988,0.012812,0.087666
1,2,0.034775,0.003513,0.045770,0.014224,0.060455,0.128714,0.102489,0.002024,0.000166,...,0.031029,0.028508,0.029647,0.105473,0.065967,0.006000,0.019060,0.010422,0.008851,0.088641
2,3,0.038096,0.003488,0.045448,0.014987,0.058411,0.127808,0.099618,0.002010,0.000042,...,0.030811,0.028797,0.029907,0.103195,0.066348,0.005957,0.020316,0.009024,0.012582,0.088017
3,4,0.037853,0.003466,0.045158,0.014422,0.058038,0.126993,0.098982,0.001997,0.000042,...,0.030615,0.028613,0.029716,0.110726,0.065925,0.005919,0.020186,0.008966,0.012502,0.087456
4,6,0.038096,0.003488,0.045448,0.014987,0.058411,0.127808,0.099618,0.002010,0.000042,...,0.030811,0.028797,0.029907,0.103195,0.066348,0.005957,0.020316,0.009024,0.012582,0.088017

In [96]:
logistico = LogisticRegression(random_state=seed)
logistico.fit(X_train, y_train)
logit_result = logistico.predict_proba(X_test)

for columna in range(logit_result.shape[1]):
    sample.iloc[:,columna+1] = logit_result[:,columna]

sample.to_csv('logistico.csv', index=False)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=1, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [103]:
logistico_S = LogisticRegression(random_state=seed)
logistico_S.fit(X_train_scaled, y_train)
logit_S_result = logistico_S.predict_proba(X_test_scaled)

for columna in range(logit_S_result.shape[1]):
    sample.iloc[:,columna+1] = logit_S_result[:,columna]

sample.to_csv('logistico_std.csv', index=False)

In [107]:
RF = RandomForestClassifier(random_state=seed)
RF.fit(X_train, y_train)
RF_result = RF.predict_proba(X_test)

for columna in range(RF_result.shape[1]):
    sample.iloc[:,columna+1] = RF_result[:,columna]

sample.to_csv('RF.csv', index=False)

In [108]:
RF = RandomForestClassifier(random_state=seed)
RF.fit(X_train_scaled, y_train)
RF_result = RF.predict_proba(X_test_scaled)

for columna in range(RF_result.shape[1]):
    sample.iloc[:,columna+1] = RF_result[:,columna]

In [109]:
GB = GradientBoostingClassifier( random_state=seed)
GB.fit(X_train_scaled, y_train)
GB_result = GB.predict_proba(X_test_scaled)
range(GB_result.shape[1])
for columna in range(GB_result.shape[1]):
    sample.iloc[:,columna+1] = GB_result[:,columna]
sample.to_csv('GB_std.csv', index=False)

In [110]:
range(GB_result.shape[1])
GB_result

array([[0.03759534, 0.00400375, 0.04245751, ..., 0.00898773, 0.01281222,
        0.08766552],
       [0.03477467, 0.00351289, 0.04576981, ..., 0.01042226, 0.00885066,
        0.08864067],
       [0.03809553, 0.00348817, 0.04544777, ..., 0.00902377, 0.0125824 ,
        0.088017  ],
       ...,
       [0.03848593, 0.0035004 , 0.04782411, ..., 0.01038519, 0.01249664,
        0.08832542],
       [0.03294899, 0.00230694, 0.04580888, ..., 0.00928651, 0.01067255,
        0.09903977],
       [0.03592354, 0.00342559, 0.04680209, ..., 0.00672848, 0.01156768,
        0.08643788]])

In [112]:
for columna in range(GB_result.shape[1]):
    sample.iloc[:,columna+1] = GB_result[:,columna]
sample.to_csv('GB_std.csv', index=False)

In [51]:
def test_roc(model, data, labels):
    if hasattr(model, "decision_function"):
        predictions = model.decision_function(data)
    else:
        predictions = model.predict_proba(data)[:,1]
    fpr, tpr, _ = sklearn.metrics.roc_curve(labels, predictions)
    return fpr, tpr

In [57]:
plt.figure()

for i, model in enumerate(classifiers):
    test_labels = model.predict(X_test)
    fpr, tpr = test_roc(model, X_test, test_labels)
    plt.plot(fpr, tpr, label=classifier_names[i])
    print(classifier_names[i]+' AUC:{}'.format(sklearn.metrics.auc(fpr, tpr)))

plt.plot([0, 1], [0, 1], 'k--')
plt.legend()
plt.xlabel('False Positive Rate', fontsize=14)
plt.ylabel('True Positive Rate', fontsize=14)

NameError: name 'sklearn' is not defined

In [31]:
## Matriz de confusión
from sklearn.metrics import confusion_matrix

mat = confusion_matrix(y_test, y_model)

plt.close()

sns.heatmap(mat, square = True, annot = True, cbar = False)
plt.xlabel('Valor predicho')
plt.ylabel('Valor real')

NameError: name 'y_train' is not defined